# Generated by Django 5.1.4 on 2025-01-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField()),
                ('questionText', models.TextField()),
                ('answer', models.TextField()),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profdata', to='solace.prof')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField()),
                ('questionText', models.TextField()),
                ('answer', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='solace.user')),
            ],
        ),
    ]
