# Generated by Django 5.1.4 on 2025-01-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0002_profdata_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='best_fit_users',
            field=models.ManyToManyField(blank=True, related_name='matched_by_profs', to='solace.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='best_fit_profs',
            field=models.ManyToManyField(blank=True, related_name='matchedByUser', to='solace.prof'),
        ),
    ]
