# Generated by Django 5.1.4 on 2025-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0003_prof_best_fit_users_user_best_fit_profs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_fit_profs',
            field=models.ManyToManyField(blank=True, related_name='matched_by_user', to='solace.prof'),
        ),
    ]
