# Generated by Django 5.1.4 on 2025-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0004_alter_user_best_fit_profs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('prof', 'Prof')], default='user', max_length=10),
        ),
    ]
