# Generated by Django 5.1.4 on 2025-01-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0005_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profdata',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profdata', to='solace.prof'),
        ),
    ]
