# Generated by Django 5.1.4 on 2025-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solace', '0007_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='budget',
            field=models.IntegerField(default=10),
        ),
    ]
